stages:
  - test
  - publish

variables:
  IMAGE_NODE: registry.gitlab.com/hnbi/shared-projects/js/docker-node-git:latest

.common:
  tags: [generic, medium]
  image: $IMAGE_NODE

test:
  extends: .common
  stage: test
  script:
    - npm ci
    - npm run test
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
    - if: '$CI_COMMIT_TAG'

publish:
  extends: .common
  stage: publish
  script:
    - npm ci
    - npm run build
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG'
